# Generated by Django 3.2.6 on 2021-09-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_phone_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profiles',
        ),
    ]
