# Generated by Django 3.2.6 on 2021-09-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='phone number'),
        ),
    ]
