# Generated by Django 3.2.6 on 2021-08-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(choices=[('', 'mobile_phone'), ('', 'cable'), ('', 'cover'), ('', 'headphones'), ('', 'screen_protector'), ('', 'computer_eqipment'), ('', 'audiovisiual'), ('', 'powerbank'), ('', 'smartwatch'), ('', 'game console'), ('', 'xiaomi accessories')], max_length=350, verbose_name='url'),
        ),
    ]
